services:
  redis:
    image: redis:7-alpine
    container_name: gm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gm_network

  gateway:
    container_name: gm-gateway
    build:
      context: ./services/servico-gateway
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - gm_network
    restart: unless-stopped

  poller:
    # container_name: gm-poller ERRO DE NOMEAÇÃO PARA O PARALELISMO
    build:
      context: ./services/servico-poller
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - gm_network
    restart: unless-stopped

  scheduler:
    container_name: gm-scheduler
    build:
      context: ./services/servico-scheduler
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - gm_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  gm_network:
    driver: bridge